version: "3"
services:
  app:
    image: node:14.15.5-alpine3.10
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    user: $DOCKER_COMPOSE_USER
    ports:
      - 7777:7777
    command: npm run dev